num_examples: None
batch_size: 20  # 64  6 
embedding_dim: 50  # 256  8
units: 128  # 1024  10
epochs: 10
checkpoint_dir: './training_cp/training_checkpoints_delex_coverage_one_ref' 
decoder_type: 'beam_search'
beam_size: 10 # beam size of 1 corresponds to greedy search
reranker_type: 'max'
gazetteer_reranker: './config/gazetteer.yaml'
pointer_generator: False  # not working
coverage_mechanism: False
reweight_cov_loss: None