num_examples: 2000
batch_size: 20  # 64  6 
embedding_dim: 50  # 256  8
units: 128  # 1024  10
epochs: 10
checkpoint_dir: './training_checkpoints_copy_mechanism' # './training_checkpoints_baseline'
decoder_type: 'beam_search'
beam_size: 10 # beam size of 1 corresponds to greedy search
reranker_type: 'gazetteer_slug'
gazetteer_reranker: './config/gazetteer.yaml'
pointer_generator: True  # not working
coverage_mechanism: False
reweight_cov_loss: None